
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARROW DIRECTION STATE SYMBOLstatements : statements statementstatements : statementstatement : STATE SYMBOL ARROW STATE SYMBOL DIRECTION'
    
_lr_action_items = {'STATE':([0,1,2,4,6,9,],[3,3,-2,-1,7,-3,]),'$end':([1,2,4,9,],[0,-2,-1,-3,]),'SYMBOL':([3,7,],[5,8,]),'ARROW':([5,],[6,]),'DIRECTION':([8,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'statement':([0,1,],[2,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',13),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',17),
  ('statement -> STATE SYMBOL ARROW STATE SYMBOL DIRECTION','statement',6,'p_statement','parser.py',21),
]
